"""`musik setup`: first-run wizard that generates this machine's config.

Creates config.yaml (from the tuned template with the user's paths),
optionally stores a Discogs token, and prints next steps. Idempotent:
re-running overwrites config.yaml, so existing settings can be migrated
by answering the prompts again.
"""

import json
import os

from . import paths

CONFIG_TEMPLATE = """\
# Generated by `musik setup` — safe to edit by hand.
directory: {library}
library: {db_file}

plugins:
    - musicbrainz
{discogs_line}    - lastgenre
    - chroma
    - fromfilename
    - duplicates
    - fetchart
    - inline

item_fields:
    multidisc: 1 if disctotal > 1 else 0

musicbrainz:
    ratelimit: 1
    ratelimit_interval: 1

discogs:
    tokenfile: {tokenfile}
    append_style_genre: yes
    search_limit: 10

lastgenre:
    auto: yes
    source: album
    count: 3
    prefer_specific: yes
    canonical: yes
    force: no

art_filename: cover

fetchart:
    auto: yes
    cautious: no
    sources:
        - filesystem
        - coverart
        - itunes
        - amazon
        - albumart
    enforce_ratio: no

import:
    copy: no
    write: yes
    move: yes
    quiet_fallback: skip
    duplicate_action: skip
    resume: no
    incremental: no
    threaded: no

match:
    strong_rec_thresh: 0.08
    medium_rec_thresh: 0.25
    rec_gap_thresh: 0.25
    max_rec:
        missing_tracks: medium
        unmatched_tracks: medium
    distance_weights:
        data_source: 0
    preferred:
        original_year: yes
    track_length_grace: 10
    track_length_max: 30

paths:
    default: $albumartist\\$original_year - $album%aunique{{}}\\%if{{$multidisc,$disc-}}$track $title
    singleton: Singles\\$artist\\$year - $title
    comp: Compilations\\$original_year - $album%aunique{{}}\\%if{{$multidisc,$disc-}}$track $title

# ---------------------------------------------------------------------------
# musik application settings (ignored by beets)
# ---------------------------------------------------------------------------
musik:
    trash_dir: {trash_dir}
    auto_accept_distance: 0.25
    review_candidates: 3
    retry_rounds: 2
    retry_cooldown_seconds: 20
"""


def _ask(prompt: str, default: str = "") -> str:
    suffix = f" [{default}]" if default else ""
    try:
        answer = input(f"{prompt}{suffix}: ").strip()
    except EOFError:
        return default
    return answer or default


def _default_library() -> str:
    return os.path.join(os.path.expanduser("~"), "Music")


def cmd_setup(library: str | None = None, discogs_token: str | None = None,
              unsorted: str | None = None) -> int:
    if library is None:
        # Scripted runs pass --library; interactive users choose here.
        library = _ask("Music library root", _default_library())
    library = os.path.abspath(library)
    trash_dir = os.path.join(library, "_trash")

    print("musik setup — generates config.yaml for this machine")
    print(f"  music library root : {library}")
    print(f"  trash dir          : {trash_dir}")
    print("  state/reports      : inside the tool folder")
    print()

    if not os.path.isdir(library):
        # The folder may arrive later; beets needs it before the first import.
        print(f"note: {library} does not exist yet — create it before importing.")

    if unsorted:
        print(f"  incoming folder    : {os.path.abspath(unsorted)}")
        print("  scan it with: python musik.py scan --root \"<folder>\"")

    # Extending an existing beets library: enter its .db path here and the
    # matching music root above — musik then imports into that library.
    db_path = _ask(
        "Beets database file (empty = new library at the root)",
        os.path.join(library, "beets-library.db"),
    )

    tokenfile = paths.DISCOGS_TOKEN_FILE
    if discogs_token is None:
        discogs_token = _ask(
            "Discogs personal access token (empty = skip, MusicBrainz only)"
        ).strip()
    if discogs_token:
        with open(tokenfile, "w", encoding="utf-8") as f:
            json.dump({"token": discogs_token, "secret": ""}, f)
        discogs_line = "    - discogs\n"
        print(f"  discogs token      : stored in {tokenfile}")
    else:
        if os.path.isfile(tokenfile):
            discogs_line = "    - discogs\n"
            print(f"  discogs token      : found existing {tokenfile}")
        else:
            discogs_line = ""
            print("  discogs            : disabled (add the token later, then re-run setup)")

    cfg = CONFIG_TEMPLATE.format(
        library=library,
        db_file=db_path,
        trash_dir=trash_dir,
        tokenfile=tokenfile,
        discogs_line=discogs_line,
    )
    with open(paths.CONFIG_FILE, "w", encoding="utf-8") as f:
        f.write(cfg)
    print(f"\nwritten: {paths.CONFIG_FILE}")

    print(
        "\nnext steps:\n"
        "  1. python musik.py scan --root \"<folder with new music>\"\n"
        "  2. python musik.py import --dry-run --unit \"<folder>\"\n"
        "  3. python musik.py import --unit \"<folder>\"\n"
        "  4. python musik.py report --verify\n"
        "see README.md for the full workflow, review.csv and the asis command."
    )
    return 0
